version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    volumes:
      - ./tests/test_repo:/app/test_repo:ro
    environment:
      - MCP_LOG_LEVEL=DEBUG
      - MCP_HOST_REPO_PATH=/app/test_repo
      - PYTHONPATH=/app
    # Remove inappropriate health check for CLI tool
    # Keep container alive for testing
    command: ["tail", "-f", "/dev/null"]
    restart: "no"

  # Optional: Add a test runner service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/src:ro
      - ./tests:/app/tests:ro
    environment:
      - PYTHONPATH=/app/src
    command: ["python", "-m", "pytest", "/app/tests", "-v"]
    depends_on:
      - mcp-server
    profiles:
      - testing
