version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - mcp-data:/mnt/data
    # Command to run the MCP server
    command: python mcp_server_main.py

volumes:
  mcp-data:
    driver: local
